# MCU name
MCU = atmega32u4

F_CPU = 16000000

ARCH = AVR8

F_USB = $(F_CPU)

OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT

OPT_DEFS += -DBOOTLOADER_SIZE=4096

ENCODER_ENABLE = yes
COMBO_ENABLE = yes
DEBOUNCE_TYPE = asym_eager_defer_pk
MOUSEKEY_ENABLE = yes
ENCODER_MAP_ENABLE = yes